### PR TITLE
BUG: Fix Unable to build documentation with Chinese

### LINKED ISSUE #517: BUG:fail to build the docs in Chinese
### Describe the bug
fail to build the docs in Chinese，but can  build the docs in English.
image

### To Reproduce
Python version: Python 3.9
Xorbits version: 0.3.0
Crucial packages:None
Full stack of the error:
image
Sphinx error:
Builder name html_zh_cn not registered or available through entry point

### PR DESCRIPTION
**Pull request by huangyong2002**
## What do these changes do?
Fix Unable to build documentation with Chinese

## Related issue number

Fixes #517 

## outcome
image
image

### CODE REVIEW

**Comment by UranusSeven** [comment]
Thanks for your contribution!

Since we are using `make html_zh_cn` for Linux and macOS, I'd prefer use the same command for windows.

To do that, you may want to have a look at `doc/make.bat`. I think there's a bug that causes #517.

What do you think?

**Comment by huangyong2002** [comment]
> Thanks for your contribution!
> 
> Since we are using `make html_zh_cn` for Linux and macOS, I'd prefer use the same command for windows.
> 
> To do that, you may want to have a look at `doc/make.bat`. I think there's a bug that causes #517.
> 
> What do you think?

Sorry, I've been trying for a long time, but I haven't been able to find the bug in  `doc/make.bat` and fix it.

**Comment by UranusSeven** [comment]
That's fine. Would you mind if someone else take over this issue?

**Comment by huangyong2002** [comment]
> That's fine. Would you mind if someone else take over this issue?

Sure, no problem.

**Comment by huangyong2002** [comment]
> That's fine. Would you mind if someone else take over this issue?

Sure, no problem.

**Pull request closed without merging**
