### PR TITLE
BUG: Fix pre-commit arg and CI node version

### PR DESCRIPTION
**Pull request by Flying-Tom**
## What do these changes do?

Fix pre-commit misused arg and CI node version in GitHub Action

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass

### CODE REVIEW

**Comment by codingl2k1** [comment]
According to the doc https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json

> This file is intended to be committed into source repositories

**Comment by Flying-Tom** [comment]
> According to the doc https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json
> 
> > This file is intended to be committed into source repositories

The `package-lock.json` file has been included already.

**Review by codingl2k1 — APPROVED** [review]
LGTM

**Review by aresnow1 — APPROVED** [review]
LGTM

**Pull request merged**
